{% if theme.search %}
    <div class="search" id="search">
        <div class="mask" id="mask"></div>
        <div class="search-wrapper syuanpi">
            <h1 id="search-header" class="syuanpi">搜索一下？</h1>
            <div class="input">
                <input type="text" id="local-search-input" results="0" name="">
            </div>
            <div id="local-search-result"></div>
        </div>
    </div>

{% endif %}
